on:
  - push

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - fixer-version: 3.24.0
          - fixer-version: 3.25.0
          - fixer-version: dev-master

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - run: composer require friendsofphp/php-cs-fixer:${{ matrix.fixer-version }} --no-interaction

      - run: ./vendor/bin/php-cs-fixer fix -vvv --diff --dry-run --rules=phpdoc_types test.php